apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/pihole-etc
    type: DirectoryOrCreate
